version: '3'

services:

  postgis:
    build: postgres
    image: jhenck57/arc_gis:postgressql
    environment:
      - POSTGRES_PASSWD=postgres
      - ENV PG_HBA "local all all trust#host all all 127.0.0.1/32 trust#host all all 0.0.0.0/0 md5#host all all ::1/128 trust"
    hostname: postgresql
    ports:
      - 5432:5432
    volumes:
      - pdb-data:/data
  qgis:
    image: qgis/qgis:release-3_4_cosmic
    links:
      - postgis
    environment:
      - WORKDIR=WORKDIR
    ports:
      - 7999:80
    volumes:
      - qgis:/gis
    networks:
      - qgis-net

  nginx:
    build: ./nginx
    image: nginx:test1
    container_name: proxy
    ports:
      - 7998:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      #- ./nginx-registry-docker/nginx/:/etc/nginx/conf.d:ro
    networks:
      - qgis-net

networks:
    qgis-net:
        driver: overlay
        
volumes:
    pdb-data:
    qgis:
